<a href="https://colab.research.google.com/github/addo561/learning-pytorch/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu124


###creating tensors

In [ ]:
scalar= torch.tensor(3)
scalar

tensor(3)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

3

In [ ]:
#vector
vector = torch.tensor([3,2])
vector

tensor([3, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])

In [ ]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[9,10,11]]])

In [ ]:
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 9, 10, 11]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][2]

tensor([ 9, 10, 11])

In [ ]:
#random tensor
ran = torch.rand(1,3,4)
ran


tensor([[[0.5865, 0.8823, 0.0245, 0.3105],
         [0.7554, 0.6356, 0.8863, 0.1008],
         [0.4880, 0.9503, 0.1127, 0.4400]]])

In [ ]:
ran.ndim

3

In [ ]:
ran.shape

torch.Size([1, 3, 4])

In [ ]:
image_rec = torch.rand(size=(3,224,224))

In [ ]:
image_rec.shape

torch.Size([3, 224, 224])

In [ ]:
image_rec.ndim

3

In [ ]:
##zero tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
##ones
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype

torch.float32

In [ ]:
##range
rang= torch.arange(0,10,2)
rang

tensor([0, 2, 4, 6, 8])

In [ ]:
#tensor like
like = torch.zeros_like(zero)
like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Tensor datatypes
nums = torch.tensor([3,4,5],dtype=None,device='cpu',requires_grad=False)
nums.dtype

torch.int64

In [ ]:
#get_info from tensor
nums.ndim,nums.shape,nums.size()

(1, torch.Size([3]), torch.Size([3]))

In [ ]:
nums.device

device(type='cpu')

In [ ]:
#Tensor manipulations
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
#or use inbuilt funcs
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,20)

tensor([21, 22, 23])

In [ ]:
#Matrix
tensor * tensor

tensor([1, 4, 9])

In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
torch.matmul(torch.rand(3,3),torch.rand(3,3))

CPU times: user 1.72 ms, sys: 0 ns, total: 1.72 ms
Wall time: 1.19 ms


tensor([[0.1636, 0.2049, 0.9271],
        [0.3766, 0.4150, 1.1135],
        [0.8215, 0.7103, 1.4415]])

In [ ]:
#transpose
torch.rand(3,2).T,torch.rand(3,2).T.shape

(tensor([[0.1130, 0.5561, 0.5323],
         [0.7246, 0.3665, 0.4506]]),
 torch.Size([2, 3]))

In [ ]:
#min,max,mean,sum
ran = torch.arange(0,10,2)
ran

tensor([0, 2, 4, 6, 8])

In [ ]:
ran.min(),ran.max()

(tensor(0), tensor(8))

In [ ]:
ran.dtype

torch.int64

In [ ]:
ran.type(torch.float32).mean()#meAN requires float32

tensor(4.)

In [ ]:
ran.sum()

tensor(20)

In [ ]:
ran = ran.type(torch.float32)

In [ ]:
mn= ran.mean()

In [ ]:
ran.argmin()#index of lowest value

tensor(0)

In [ ]:
ran.argmax()#index of highest value

tensor(4)

In [ ]:
ran[0]

tensor(0.)

In [ ]:
ran[2]

tensor(4.)

In [ ]:
 #reshaping,stacking,squeezing and unsqueezing,view,permute
x = torch.arange(1,10)
x.shape

torch.Size([9])

In [ ]:
x_reshaped = x.reshape(9,1)

In [ ]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_reshaped.shape

torch.Size([9, 1])

In [ ]:
z = x.view(9,1)
z

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
z[2,:] = 4
z,x

(tensor([[1],
         [2],
         [4],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 tensor([1, 2, 4, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9]])

In [ ]:
#squeezing and unsqueezing
new = x_reshaped.squeeze()
new.shape,new


(torch.Size([9]), tensor([1, 2, 4, 4, 5, 6, 7, 8, 9]))

In [ ]:
new.unsqueeze(dim=0).shape,new.unsqueeze(dim=0)

(torch.Size([1, 9]), tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9]]))

In [ ]:
#permutes
x = torch.rand(size=(224,224,3))
torch.permute(x,(2,0,1)).shape,x.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [ ]:
 x_stacked

tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stacked.shape

torch.Size([4, 9])

In [ ]:
x_stacked[2][7]

tensor(8)

In [ ]:
x_stacked[2:4]

tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stacked[:,3][0]

tensor(4)

In [ ]:
import numpy as np
array = np.array([2,1])
tensor = torch.from_numpy(array)
tensor.dtype,array.dtype

(torch.int64, dtype('int64'))

In [ ]:
tensor = torch.arange(1,10)
numpy = tensor.numpy()
tensor ,numpy

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#reproducibility
tensor1 = torch.rand(1,10)
tensor2 = torch.rand(1,10)
tensor1==tensor2

tensor([[False, False, False, False, False, False, False, False, False, False]])

In [ ]:
Random_seed = 42
torch.manual_seed(Random_seed)
tensor3 = torch.rand(1,10)

torch.manual_seed(Random_seed)
tensor4 = torch.rand(1,10)
tensor3==tensor4


tensor([[True, True, True, True, True, True, True, True, True, True]])

In [ ]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [ ]:
#put tensor on gpu
tensor = torch.tensor([3,2])
tensor.device

device(type='cpu')

In [ ]:
tensor.to('cuda') #to gpu
tensor.cpu()#to cpu

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx